#!/usr/bin/env sh
trap finally INT

elapsed=0

to_string() {
    t=$1
    days=$((t / 86400))
    hours=$(printf %02d $(((t % 86400) / 3600)))
    minutes=$(printf %02d $(((t % 3600) / 60)))
    seconds=$(printf %02d $((t % 60)))

    if [ $days -ne 0 ]; then
        printf '%sd %s:%s:%s\r' "$days" "$hours" "$minutes" "$seconds"
    else
        printf '%s:%s:%s\r' "$hours" "$minutes" "$seconds"
    fi
}

main() {
    start_time=$(date +%s)

    while :; do
        elapsed=$(($(date +%s) - start_time))
        printf '%s' "$(to_string ${elapsed})"
        sleep 1
    done
}

finally() {
    printf '\r%s\n' "$(to_string ${elapsed})"
    exit 0
}

main
